.travis.yml

update to check for travis

---

LICENSE

update license file in root

---

HACKING.md
mk/test.mk

Add test-acceptance target

---

icsp/deploymentjobs.go
icsp/icsp.go
icsp/icsp_test.go
icsp/netconfig.go
icsp/netconfig_test.go
icsp/servers.go

fix #48 applying netconfig for post deploy

---

README.md

add build status indicator

---

Dockerfile

Signed-off-by: Edward Raigosa <edward.raigosa@gmail.com>

Update dockerfile to be equal to docker-oneview project

---

ov/storage.go
ov/storage_test.go

Fix san storage errors we get from OV when trying attached storage

---

ov/storage.go
ov/storagev2.go

Testing is showing we need some of these to be optional, lets tune the settings
Signed-off-by: Edward Raigosa <wenlock@hp.com>

Trun omit back on for some storage options

---

Makefile.inc

Signed-off-by: Edward Raigosa (wenlock) <wenlock@hpe.com>

Lets improve how we sed remotes

---

build/validate-gofmt
glide.lock
mk/main.mk
mk/validate.mk
vendor/github.com/docker/machine/docs/drivers/aws.md
vendor/github.com/docker/machine/drivers/azure/azureutil/tenantid.go
vendor/github.com/docker/machine/drivers/digitalocean/digitalocean.go
vendor/github.com/docker/machine/drivers/virtualbox/virtualbox_windows.go
vendor/github.com/docker/machine/version/version.go

- remove other Godeps checks in folders

Update the vendor folder with 0.8 lib changes

---

ov/enclosure_group.go
ov/profile_templates.go
ov/profile_templates_test.go
ov/profiles.go
ov/server_hardware_type.go
ov/server_hardware_type_test.go
ov/storage_volume.go
ov/storage_volume_test.go
test/data/config_EGSL_tb200.json

Signed-off-by: Dian Hansen <dian.hansen@hpe.com>

add additional resources, update enclosure_group

---

ov/fc_network.go
ov/fc_network_test.go

add fc network resource

---

version.go

bump version to 0.8.1

---

i3s/auth.go
i3s/auth_test.go
i3s/deployment_plan.go
i3s/deployment_plan_test.go
i3s/i3s_test.go
i3s/task.go
i3s/task_test.go
test/data/config_EGSL_tb200.json

The format for this is similar to the other resources so I added the basic methods and testing but I won't know if it works until we get access to i3s. Let me know if this isn't a good idea @wenlock.
Signed-off-by: matthew-frahry <matthew.frahry@hpe.com>

I3s task and job

---

i3s/golden_image.go
i3s/golden_image_test.go
test/data/config_EGSL_tb200.json

Signed-off-by: matthew-frahry <matthew.frahry@hpe.com>

InitialGoldenImage

---

i3s/os_buildplan.go
i3s/os_buildplan_test.go
test/data/config_EGSL_tb200.json

This should be good to go when #80 is merged in.
Signed-off-by: matthew-frahry <matthew.frahry@hpe.com>

InitialOSBuildPlan

---

i3s/plan_script.go
i3s/plan_script_test.go
test/data/config_EGSL_tb200.json

Signed-off-by: matthew-frahry <matthew.frahry@hpe.com>

Add plan scripts

---

icsp/servers.go
ov/profile_templates.go

Signed-off-by: Matthew Frahry <matthew.frahry@hpe.com>

Add and update create/get methods

---

ov/connectionv3.go
ov/os_deployment_plan.go
ov/power_state.go
ov/profiles.go
ov/profilesv3.go
ov/server_hardware.go

@wenlock, the manageI3SConnections block is a lot smarter about how to do the connection piece. Let me know what you think and what needs to change.

Customize server v3

---

endpoints-support.md

Add/endpoints support.md

---

examples/storage_volume.go

Updated the variable usage as per the updated variable declaration

Updating variable names

---

endpoints-support.md
examples/storage_volume_attachment.go
ov/storage_volume_attachment.go

Support for storage volume attachments until API800 from API500
- [] Changes are documented in the CHANGELOG.

Storage volume attachments

---

endpoints-support.md
examples/storage_pool.go
ov/storage_pool.go

Support for storage pools until API800 from API500
- [] Changes are documented in the CHANGELOG.

Storage pools

---

examples/enclosure.go
ov/enclosure.go

**Description**
Added all the parameters for the Enclosure resource
**Check List**

Missing fields in struct for enclosure resource.

---

examples/enclosure_group.go
ov/enclosure_group.go

**Description**
Added all the parameters for the Enclosure Group resource
**Check List**

Adding all the missing parameters for enclosure group

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
version.go

Added CHANGELOG.md to track versions, issues and improvements
[Fixes #108]

Added CHANGELOG to track versions, issues and improvements

---

examples/server_hardware.go
ov/server_hardware.go
ov/server_hardwarev2.go

Field Name corrected in server hardware struct

Field Name corrected in server hardware struct

---

ov/logical_interconnects.go

Added missing structure for logical interconnect

Bug fix for logical interconnect.

---

ov/logical_interconnect_group.go
ov/logical_interconnects.go

logical interconnect struct fix.
logical interconnect struct fix.

logical interconnect struct fix.

---

examples/server_hardware_type.go
ov/server_hardware_type.go

Added missing fields in ServerHardwareType Resource
No

Added missing fields in ServerHardwareType Resource

---

CHANGELOG.md
examples/server_profile.go
ov/profiles.go

Bugfix for server profile template.

---

ov/connection.go
ov/connectionv3.go

Connections body updated to support 800

Connections body updated to support 800

---

endpoints-support.md
examples/network_set.go
ov/network_set.go

Adding support for Network set to be able to pull their status for example for monitoring purposes
None

Network set

---

ov/logical_interconnect_group.go

Field attribute updated to support lig internal network update/create.

Field attribute updated.

---

ov/connection.go
ov/profiles.go
ov/profilesv3.go
ov/storage.go

adding additional attributes to the structures for server profile creation

Struct update

---

examples/storage_volume.go
ov/storage_volume.go

Struct fix for volume

---

ov/storage.go

San Storage struct fix.
Issue with the never version of SAN Volume struct.

Storage struct fix.

---

examples/server_hardware.go
ov/server_hardware.go
test/ov/profiles_test.go

Signed-off-by: Madhav <madhavb@hpe.com>
Adding API1000 support to Server hardware

Server hardware - Api1000

---

CHANGELOG.md
endpoints-support.md
examples/tasks.go

Signed-off-by: AnushaY1916 <anuanusha471@gmail.com>
API 1000 support for Task
NA

API 1000 support for Task

---

CHANGELOG.md
endpoints-support.md
examples/deployment_plan.go

Upgraded support for Deployment plan to 1020.

Upgraded support for Deployment plan to 1020.

---

CHANGELOG.md

Changelog for release 1.2

---

CHANGELOG.md

[SDK  version 1.30 release]
[]

SDK_1.30_release

---

CHANGELOG.md

support login msg ack

---

ov/hypervisor_cluster_profile.go

Added get by name  method for HyperClusterProfile resource

---

CHANGELOG.md
ov/profiles.go
test/data/config_EGSL_tb200.json
test/ov/profiles_test.go

Get available server hardwares
Fixes #56

Get available server hardwares for SP

---

CHANGELOG.md
README.md
examples/hypervisor_cluster_profile.go

release 1.5.0 pr

---

ov/profiles.go
ov/storage.go

Updated changes which were required while working on OV for terraform
N/A

Tf changes

---

ov/storage.go

Updated storage struct inorder to correct TF Issues for SP/Volume Creation.
N/A

Updated Storage Struct

---

CHANGELOG.md
README.md
ov/config.go
ov/ov.go

Api deprecation changes

---

.github/workflows/main.yml
CHANGELOG.md

It pushes Docker Image when there is a new release created in GitHub
NA

Automated Docker Image publish

---

CHANGELOG.md
endpoints-support.md
examples/deployment_plan.go

Support I3S API 2000 for Deployment Plan Resource.
N/A

Support to I3S Deployment Plan

---

examples/logical_interconnect_groups.go
ov/logical_interconnect_group.go

[Fixed LIG and added example for uplink set update]
[https://github.com/HewlettPackard/terraform-provider-oneview/issues/206]

Fixed LIG and added example for uplink set update

---

.github/workflows/main.yml
CHANGELOG.md
README.md

updated changes for v1.7 release
N/A

PR for v1.7 release

---

ov/profiles.go

[Describe what this change achieves]
[Fixes #283]

Allow creation of SP with unassinged hardware

---

examples/server_hardware.go
examples/server_hardware_types.go
examples/server_profile_templates.go
examples/server_profiles.go
examples/storage_pools.go
examples/storage_systems.go
examples/storage_volume_attachment.go
examples/storage_volume_templates.go
examples/volumes.go

server_hardware.go
server_hardware_types.go
server_profile_templates.go
server_profiles.go
storage_pools.go
storage_systems.go
storage_volume_templates.go
volumes.go
N/A

Updated SH, SHT, SP, SPT, St_pool, St_sys, SVT, Volumes example for automation Script

---

CHANGELOG.md
examples/server_hardware.go
ov/server_hardware.go

Added Enhancement for GetIloIPAddress() in ServerHardwareList Method. 
#286

Issue 286 - GetIloIPAddress() 

---

CHANGELOG.md
README.md

Issue 185 - Updated ReadMe

---

ov/enclosure.go

[This fixes the terraform build issue
[issue 235 in terraform]

fixed build error

---

ov/logical_interconnect_group.go

Added portFlapProtection field for OV 5.6
[]

Added portFlapProtection

---

CHANGELOG.md
ov/logical_interconnect_group.go

LIG - NTP Configuration struct  variable types were not correctly defined.

fixed NTP Struct

---

.github/workflows/main.yml
CHANGELOG.md
README.md

release PR

---

.github/workflows/main.yml
CHANGELOG.md
README.md

Release6.0

---

examples/server_hardware.go
ov/server_hardware.go

server_hardware_issue

---

.github/workflows/main.yml
CHANGELOG.md
README.md

Release PR for OV6.1

---

ov/profiles.go
ov/profilesv3.go
ov/storage.go

[SPT individual attributes addition]

SPT individual attributes addition

---

examples/tasks.go
ov/task.go

Task's Patch fix for TF

---

ov/profile_templates.go
ov/profiles.go

added MPsettings for update as well
N/A

added MPsettings for update as well

---

CHANGELOG.md

OV 6.2 release

---

ov/profiles.go

added omitempty to hideunsedflexnics to support DL server

added omitempty to hideunsedflexnics

---

ov/enclosure_group.go

Added ipv6 rangeuris

---

ov/profile_templates.go
ov/profiles.go

To Support hostname in TF

---

ov/logical_interconnect_group.go

added desiredFecMode in LIG

---

CHANGELOG.md
examples/server_hardware.go
ov/server_hardware.go
ov/server_hardware_type.go
test/ov/server_hardware_test.go

Support Delete for DL

---

ov/logical_enclosure.go
ov/profiles.go

[Added inital scope uri in le and sserver profile description in profile]
[1]

Added inital scope uri in le and sserver profile description in profile

---

ov/profiles.go

[Describe what this change achieves]
[]

Use-description-from-template

---

ov/profile_templates.go
ov/profiles.go

Support hostname in iLO Settings

Support hostname in iLO Settings

---

examples/server_profile_templates.go
ov/profile_templates.go
ov/profiles.go

Update struct name for iloHost

Update struct name for iloHost

---

examples/connection_templates.go
ov/connection_templates.go

Added GetByUri for Connection Template

Added GetByUri for Connection Template

---

ov/profiles.go

Update cleanup function

---

examples/firmware_drivers.go
ov/firmware_drivers.go

[Added GetFirmwarebyNameAndVersion method]

Added GetFirmwarebyNameAndVersion method

---

CHANGELOG.md

Release OV 6.5

---

ov/profile_templates.go
ov/profiles.go
ov/server_hardware_type.go

[Added additional attributes to local account in iLO configuration]
[]

added attributes for local account

---

ov/profile_templates.go

[Describe what this change achieves]

added spt ilo changes

---

ov/profiles.go

[Removed unwanted spt description from sps]
[#359 ]

Removed unwanted spt description from sp

---

examples/storage_volume_templates.go
examples/volumes.go
ov/storage_volume_template.go

[Describe what this change achieves]

Added get root template

---

ov/firmware_drivers.go

[fw driver fix for terraform issue 463s]

fw driver fix for terraform issue 463

---

ov/storage_volume.go

[Added description to storage volume]
[]

Added description to storage volume

---

ov/storage.go

[fix for issue474 from terraform]

fix for issue474 from terraform

---

CHANGELOG.md
examples/logical_interconnect_groups.go
ov/logical_interconnect_group.go

[Portnum change from relative value]
[1]

Portnum change from relative value

---

ov/profiles.go

[Create SP without type field]

Create SP without type field
