icsp/build_plan.go, testconfig/testconfig.go
When we look for os build plans, we could run into hanging the docker-machine
driver with using --debug.  This removes the debuging log output for
data returned on the call for get build plans.
We've also added an option to control debug output in our test cases
for the logger
=> fix buid plan hanging with --debug

icsp/icsp.go, icsp/icsp_test.go, icsp/server_customattribute.go, icsp/servers.go
We needed to fix how we get ipv4 from public_ip
so that we don't get an empty value, and move on to check
public_interface value.   public_ip should be used for
dns alias and such.
=> Fix how we get ipv4 for (#48)

icsp/auth.go, icsp/auth_test.go
This gives refreshlogin in icsp api's the ability
to detect when we have a timedout token, and
refreshes it so we can continue without issues.
=> Fix for #40: implement ideltimeout checks

ov/auth.go, ov/auth_test.go
We need to have a way to detect when the idle time for a session
is now expired, and renew it when it has
=> fix #40: ov session expires cause api execution failure

ov/storage.go, ov/storagev2.go
- Fix typo with volumeShareable property
- fix all bools to exist even when empty
=> Fix #67: san storage options need to be visible even when not set

.drone.yml, .travis.yml, Dockerfile, Makefile, rest/method_test.go, rest/netutil.go
Update rest method for golang 1.6 so that we specifically use String() method
Update testing to be in 1.6
Signed-off-by: Edward Raigosa <wenlock@hp.com>
=> Fix for golang 1.6

Makefile, Makefile.inc, README.md
We'll also have to update the travis.yml build so that USE_CONTAINER=false
but GH_REPO and GH_USER are no longer needed and can be hard coded.
Fixes Issue #61
=> Fixes #61 local build so that USE_CONTAINER=true is the default

HACKING.md, Makefile, icsp/api_version_test.go, liboneview/api_support.go, liboneview/api_support_test.go, liboneview/version_test.go, ov/api_version_test.go, ov/server_hardware.go, ov/server_hardware_test.go, test/data/config_EGSL_tb200.json, testconfig/testcases.go
Newer versions of OneView are not being
detected as v2 api.   This loosens the
v2 version detection to include unkown versions
in favor of using v2 api.
- add some test case methods for equality testing
- provide some methods for testing in docker
- update acceptance test case for dev on new hw
=> fix issue #94 - issue with v2 detection

i3s/i3s.go, i3s/i3s_test.go, mk/main.mk
Lets start working on Image Streamer 3.0 (I3S)
This work will be introduced as several PR's
subsequent to this one.  Goal for this PR
is to establish the new folder, and entry-point
client for the i3s portoion of the goland sdk.
- adds new package and testing called i3s, so now
we have an I3SClient to work with.
=> Add Image Streamer API support

rest/netutil.go, testconfig/testcases.go, utils/stringy.go
Hello!
I made a couple of minor modifications here. Some are just best practices (although I'm not sure if you guys accept package-level vars), and others are just functional improvements.
* I removed reflection from the package, since it was pretty much not needed. There was a type casting so that saves a couple of keystrokes plus makes it more resilient, and avoid creating a slice.
* I moved the client and transport to a package-level rather than function level, this is so you can reuse the same client and prevent some nasty problems when creating it multiple times. This also allows to reuse the same transport mechanism.
I'm @mbfrahry's coworker btw.
=> Remove reflection from the package. Minor opts.

ov/fc_network.go, utils/helpers.go, utils/helpers_test.go
Hello everyone,
With a bit of free time, I added two more simple tests, but also changed some things:
When `json.Unmarshal()`ing, there was a cast to take `data` which is the http response, to be casted to `[]byte`. This was not needed since the value is already a byte slice. I did it in one file, just to see, then I can propagate the same change to all other files.
I rewrote the (incorrectly spelled) `Sanatize()` function based on the condition... Previously, it was...
```go
func Sanatize(s string) string {
if strings.LastIndex(s, "/") > 0 {
s = strings.Trim(s, "/")
}
return s
}
```
... Which I understand as: if it ends in `/` then remove them. The problem is that `Trim()` not only removes the final slashes, but also the ones at the beginning. I rewrote it so it only accounts for those …
=> Add more tests. Avoid casting bytes from the response.

ov/connectionv3.go, ov/profilesv3.go
Lets change from a hard-coded deploy.net value to new custom attribute
that can help us identify the deployment network to use.  To be provided
by the consumer.
=> remove hard coded deployment network call

rest/method.go, rest/method_test.go
Adding an enhancement to Method within `github.com/HewlettPackard/oneview-golang/rest` package to allow for use of the OneView 310 RemoteSupport API.
Partial enhancement for [issue#38](https://github.com/HewlettPackard/oneview-golang/issues/38)
=> Support for HTTP "PATCH" Method

.travis.yml, Dockerfile, README.md, test/i3s/i3s_test.go, test/icsp/icsp_test.go, test/ov/ov_test.go, test/ov/profile_templates_test.go, test/ov/storage_volume_test.go
**Description**
Upgrading go version and removing go get to download dependencies
**Issues Resolved**
Fixes #106
**Check List**
=> Upgrading go version and removing go get to download dependencies

ov/logical_interconnect_group.go
This adds the interconnectBaySet field that was introduced in 300 to the LogicalInterconnectGroup struct.  This field is required to fix https://github.com/HewlettPackard/terraform-provider-oneview/issues/47
Signed-off-by: Adam Robinson <adarobin@umich.edu>
=> Add interconnectBaySet to LogicalInterconnectGroup

.gitattributes, rest/netutil.go
The currently displayed error messages aren't always easy to follow.  I have added some more details to the message to make troubleshooting a bit easier.
For example, this message from Terraform left me scratching my head a bit:
```
* oneview_logical_interconnect_group.lig: Error in response: Only one enclosure is present in the Logical Interconnect Group
Response Status: 400 Bad Request
```
With this code, I get this error message with some more clarity:
```
* oneview_logical_interconnect_group.lig: Error in response: A Highly Available Logical Interconnect Group must contain at least 2 enclosures.
Response Status: 400 Bad Request
Response Details: Only one enclosure is present in the Logical Interconnect Group
```
I also updated .gitattributes to mark *.png files as binary.  Otherwise, …
=> Show better error messages

ov/logical_interconnect_group.go
Changed the Uplink_set struct name to Uplink_sets as it will be conflicting with the Uplink_set struct in Uplink_set resource file, and also naming as per rest API doc.
struct name change for Uplink_set in LIG API800
=> changed the uplinkset struct name as it is not in sync with Rest API doc

ov/logical_interconnect_group.go
Per the API documentation, "For Virtual Connect SE 40Gb F8 Module, SNMPv3 cannot be disabled and it is enabled by default."
This commit adds the v3Enabled option to the SNMP structure for Logical Interconnect Groups.  Without this option, it is not possible to modify a Logical Interconnect Group using a Virtual Connect SE 40Gb F8 in Terraform.
=> Add support to LIG for configuring SNMPv3

ov/ethernet_network.go, ov/uplink_set.go
Corrected the Uplink set struct and added the missing parameter in Ethernet struct
=> corrected uplink struct and added missing parameter in ethernet struct

ov/enclosure.go
Change PartitionID Type from String to Int as described in the REST API Documentation
partitionID Numeric value of partition id within an enclosure. integer required read only
None Documented
=> Enclosure - PartitionID Type to INT

ov/auth.go
OneView has the ability to force acknowledgment of the login message before allowing access to the appliance.  When that option is enabled, then the current OneView client will always fail to authenticate to the appliance.
This change simply adds a field to the LoginSession POST request that says that it accepts the login message.
This is ignored if the force acknowledgment hasn't been configured.
No issue created
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-golang/208)
=> support login message ack

CHANGELOG.md, rest/netutil.go
Added fix to reset query parameters for every REST call.
Fixes #141
=> fixed issue 141

CHANGELOG.md, README.md
Release PR for 5.4 Version,
API 2000
=> updated changelog for release

CHANGELOG.md, examples/server_hardware.go
Modified the example and changelog
#301
=> modified_changelog_and_examples

ov/storage.go
[A Fixed san storage attribute for initialscope uris and tcp port]
[]
=> A Fixed san storage attribute for initialscope uris and tcp port

CHANGELOG.md, ov/storage_volume.go
Changes datatype of Id in DeviceSpecificAttributes struct to int to align it with oneview
#368
=> Datatype change for Id in DeviceSpecificattributes

examples/server_profiles.go, ov/profiles.go
This PR introduces the feature to specifiy the force flag for the server profile creation:
> https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cicf-api/en/index.html#rest/server-profiles
```
**force**
Comma-separated list of flags for ignoring specific warnings. Calls may use "all" (or "true") to pass all ignore flags, or "none" (or "false") to pass none of them. Quotes are optional. The supported comma-separated list of flags are:
ignoreSANWarnings: When provided, the operation will ignore warnings for non-critical issues detected in the SAN storage configuration. 
ignoreServerHealth: When provided, the operation will ignore the check to verify that the selected server's health is OK. 
ignoreLSWarnings: When provided, the operation will ignore the validation warnings from …
```
=> feat(serverprofile): add force param to serverprofile creation

ov/config.go
Load configuration from a file with an absolute path
Fixes #422
=> Add function to create configuration from fullpath defined file
